name: monitoring
namespace: monitoring
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki.
labels:
  app-type: monitoring
  app-group: services

apps:
  - name: prometheus
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.x
      chart: "prometheus"
      valuesFile: "prometheus.yaml"
  - name: thanos
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.x
      chart: "thanos"
      valuesFile: "thanos.yaml"
  - name: loki
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.2.x
      chart: "loki-stack"
      valuesFile: "loki.yaml"
  - name: jaeger-operator
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.x
      chart: "jaeger-operator"
      valuesFile: "jaeger-operator.yaml"
