name: monitoring
namespace: monitoring
destinationServer: https://env-ps-test-44fff1eb.hcp.westeurope.azmk8s.io:443
description: All the monitoring apps, including but not limited to prometheus, grafana, thanos, loki.

project:
  name: monitoring
  sourceRepos:
    - '*'
  destinations:
    - namespace: kube-system
      server: https://env-ps-test-44fff1eb.hcp.westeurope.azmk8s.io:443

apps:
  - name: prometheus
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.11
      chart: "prometheus"
      valuesFile: "prometheus.yaml"
  - name: thanos
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.8
      chart: "thanos"
      valuesFile: "thanos.yaml"
  - name: loki
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.2.5
      chart: "loki-stack"
      valuesFile: "loki.yaml"
  - name: jaeger-operator
    source:
      repoURL: 'https://open-olympus-project.github.io/repo-helm/'
      targetRevision: 0.1.3
      chart: "jaeger-operator"
      valuesFile: "jaeger-operator.yaml"
