name: apache-drill
namespace: apache-drill
description: Apache-drill instance
labels:
  app-type: apache-drill
  app-group: applications

apps:
  - name: apache-drill
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.x
      chart: drill
      valuesFile: "apache-drill.yaml"