traefik:
  deployment:
    enabled: true
    # Can be either Deployment or DaemonSet
    kind: DaemonSet

  ingressClass:
    fallbackApiVersion: "v1"
    enabled: true
    isDefaultClass: true

  logs:
    access:
      enabled: true

  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-resource-group: {{ .Values.ingress.LoadBalancerResoureGroup | quote }}

    spec:
      loadBalancerIP: {{ .Values.ingress.loadBalancerIP }}

  additionalArguments:
  - --metrics.prometheus=true