name: networking
namespace: networking
destinationServer: https://env-ps-test-44fff1eb.hcp.westeurope.azmk8s.io:443
description: networking services like ingress, cert-manager.

project:
  name: networking
  sourceRepos:
    - '*'
  destinations:
    - namespace: kube-system
      server: https://env-ps-test-44fff1eb.hcp.westeurope.azmk8s.io:443
    - namespace: nidhogg
      server: https://env-ps-test-44fff1eb.hcp.westeurope.azmk8s.io:443

apps:
  - name: traefik
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.2.x
      chart: "traefik"
      valuesFile: "traefik.yaml"
  - name: cert-manager
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.1.x
      chart: "cert-manager"
      valuesFile: "cert-manager.yaml"
  - name: cert-manager-issuer
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.1.x
      chart: "cert-manager-issuer"
      valuesFile: "cert-manager-issuer.yaml"
