name: networking
namespace: networking
description: networking services like ingress, cert-manager.

project:
  name: networking
  sourceRepos:
    - '*'
  destinations:
    - namespace: kube-system
      server: https://env-ps-test-d3cc7d1a.hcp.westeurope.azmk8s.io/
    - namespace: nidhogg
      server: https://env-ps-test-d3cc7d1a.hcp.westeurope.azmk8s.io/

apps:
  - name: traefik
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.2.x
      chart: "traefik"
      valuesFile: "traefik.yaml"
  - name: traefik-forward-auth
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.1.x
      chart: "traefik-forward-auth"
      valuesFile: "traefik-forward-auth.yaml"
  - name: cert-manager
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.1.x
      chart: "cert-manager"
      valuesFile: "cert-manager.yaml"
  - name: cert-manager-issuer
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm/"
      targetRevision: 0.1.x
      chart: "cert-manager-issuer"
      valuesFile: "cert-manager-issuer.yaml"
