name: adapters
clusterService: false
namespace: adapters
description: adapters
labels:
  app-type: adapters
  app-group: applications

apps:
  - name: adapters-secrets
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm"
      targetRevision: 0.1.3
      chart: "lethe"
      valuesFile: "lethe.yaml"
  - name: a-ikontrol
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.x
      chart: "osiris-scheduler"
      valuesFile: "a-ikontrol.yaml"
  - name: a-jao-monthly
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.x
      chart: "osiris-scheduler"
      valuesFile: "a-jao-monthly.yaml"
  - name: a-jao-yearly
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.x
      chart: "osiris-scheduler"
      valuesFile: "a-jao-yearly.yaml"
  - name: a-nationalbanken
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.x
      chart: "osiris-scheduler"
      valuesFile: "a-nationalbanken.yaml"
  - name: a-nordpool-special-regulation
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.x
      chart: "osiris-scheduler"
      valuesFile: "a-nordpool-special-regulation.yaml"
  - name: a-svk-primary-regulation
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.x
      chart: "osiris-scheduler"
      valuesFile: "a-svk-primary-regulation.yaml"