name: datacatalog
clusterService: false
namespace: datacatalog
description: datacatalog
labels:
  app-type: datacatalog
  app-group: applications

apps:
  - name: datacatalog-secrets
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm"
      targetRevision: 0.1.3
      chart: "lethe"
      valuesFile: "lethe.yaml"
  - name: datacatalog-frontend
    source:
      repoURL: "https://github.com/Open-Dataplatform/datacatalog-frontend"
      targetRevision: feature/image-pull-sec
      path: "chart"
      valuesFile: "frontend.yaml"
  - name: datacatalog-backend
    source:
      repoURL: "https://github.com/Open-Dataplatform/datacatalog-backend"
      targetRevision: feature/new-ingress
      path: "chart"
      valuesFile: "backend.yaml"
