scName: poc
nameSuffix: dev

vaultServer: <vault-server>
lokiServer: <loki-server>

destinationServer: localhost:443

ingress:
  host: <host>
  loadBalancerIP: <ip>
  LoadBalancerResoureGroup: <rg>
  certmanagerissuer: <cluster-issuer>
  # className: ingress-traefik

applications:
  argo-workflows: true
  argo-events: true
  argo-events-setup: true
  argo-events-azure: false
  cert-manager: true
  cert-manager-issuer: true
  external-secrets: true
  traefik: true
  jaeger-operator: true
  loki: true
  minio-operator: true
  prometheus: true
  thanos: true
  traefik-forward-auth: true
  vault: true

  # Data catalog
  datacatalog-secrets: true
  datacatalog-frontend: true
  datacatalog-backend: true

  # Osiris
  osiris-secrets: true
  osiris-ingress: true
  osiris-egress: true

  # Adapters
  adapters-secrets: true
  a-ikontrol: true

  # Transformations
  transformations-secrets: true
  t-datahub-bi-hydro: true
  t-datahub-bi-own-consumption: true
  t-dmi-weather: true
  t-i2et-gtms-alloc-bi: true
  t-i2et-gtms-balance-system-bi: true
  t-i2et-gtms-biocertificate-bi: true
  t-i2et-gtms-data-h-bi: true
  t-i2et-gtms-invoice-lines-bi: true
  t-i2et-gtms-nom-bi: true
  t-i2et-nordpool: true
  t-i2et-nordpool-special-regulation: true
  t-i2et-sf6: true
  t-ikontrol: true
  t-jao-monthly: true
  t-jao-yearly: true
  t-jao2eds: true
  t-neptun-1d: true
  t-neptun-1h: true
  t-neptun-3m: true
  t-neptun-masterdata: true
  t-oilcable-leakdetection: true
  t-svk-primary-regulation: true

images:
  transform-ingress2event-time:
    test: "latest-test"
    prod: "0a37dca"

  transform-datahub-bi:
    test: "latest-test"
    prod: "b7128e1"

  transform-dmi-weather:
    test: "latest-test"
    prod: "bba83b8"

  transform-jao:
    test: "latest-test"
    prod: "83d91d0"

  transform-neptun:
    test: "latest-test"
    prod: "f3b0596"

  transform-neptun-masterdata:
    test: "latest-test"
    prod: "d4a8b21"

  transform-ikontrol:
    test: "latest-test"
    prod: "8270046"

  transform-oilcable-leakdetection:
    test: "latest-test"
    prod: "6440573"

  transform-jao2eds:
    test: "latest"
    prod: "5f75fef"

  transform-svk-primary-regulation:
    test: "latest-test"
    prod: "7833a0b"

# Environment based guids
guids:
  SF6_GAS_monitoring_data:
    prod: ebc4f329-b59e-40a5-a882-08d8de4f4dcb

  SF6_GAS_monitoring_data_Aggregated:
    prod: d1821849-f127-4dc8-a883-08d8de4f4dcb

  DMI_Forecast_EnetNEA_20:
    test: a1248010-e46e-4491-11de-08d8fda51d00
    prod: f9561592-55dc-4af3-9be7-08d90a4e650d

  DMI_Forecast_Aggregated:
    test: 1bf31823-4e55-4956-88cc-08d9834acce7
    prod: 2c844464-5872-4d60-dc2c-08d945e7e910

  JAO_Monthly:
    prod: 4fe6499b-23f9-4013-adfd-08d8fda4ba53

  JAO_Aggregated_Monthly:
    prod: 48c22d75-940a-41e9-adff-08d8fda4ba53

  JAO_Yearly:
    prod: ff29b8b4-cd84-4253-a7aa-08d91a00b8e7

  JAO_Aggregated_Yearly:
    prod: 2d20ccdc-d9f3-4a99-a7a9-08d91a00b8e7

  GT_Biocertificate_BI:
    prod: b133dd7a-f1e8-48db-fc33-08d8b6fedea4

  GT_Biocertificate_BI_validated:
    prod: ec135591-bbf6-4e69-eecd-08d9628f61e5

  GT_DATA_H_BI:
    prod: da650d2c-2780-44dc-6b3c-08d876589e90

  GT_DATA_H_BI_validated:
    prod: 726dd6be-c485-4cf9-eecf-08d9628f61e5

  GT_Invoice_Lines_BI:
    prod: 471d3e34-b843-4298-fc34-08d8b6fedea4

  GT_Invoice_Lines_BI_validated:
    prod: 2cb9c571-3a5a-4d5c-eed1-08d9628f61e5

  GT_Balance_System_BI:
    prod: 0f3897d5-0c57-4967-7de4-08d86b849d90

  GT_Balance_System_BI_validated:
    prod: 55b1015a-e04e-442c-eed4-08d9628f61e5

  GT_Alloc_BI:
    prod: 02480cbc-5361-43ab-e1d8-08d86464f17e

  GT_Alloc_BI_validated:
    prod: 6c460d49-a450-48c2-82ff-08d9661b40e3

  GT_Nom_BI:
    prod: fecfb55e-4637-4ff6-af49-08d86c4300e8

  GT_Nom_BI_validated:
    # This does not exist in datacatalog??
    prod: 50a24e8a-1d6e-4de5-13c3-08d966dc19d5

  Elspot_Prices_Nordpool_Ingress:
    prod: be8e3fd7-e0ce-43d4-eed5-08d9628f61e5

  Nord_Pool_Elspot_prices_and_volumes:
    prod: 531fa345-81f7-4878-eed7-08d9628f61e5

  Neptun_3M:
    prod: 3f0d123a-377f-49c7-115b-08d925bcbaf2

  Neptun_3M_validated:
    prod: 49408b8e-54fd-4d78-115d-08d925bcbaf2

  Neptun_1H:
    prod: 5bcbaade-8c9f-41fe-115a-08d925bcbaf2

  Neptun_1H_validated:
    prod: 0d80b6fc-fcfb-4848-1153-08d925bcbaf2

  Neptun_1D:
    prod: 939ac086-65c1-492b-9be1-08d90a4e650d

  Neptun_1D_validated:
    prod: 5466d7cc-77cb-4cd1-1155-08d925bcbaf2

  Neptun_masterdata:
    prod: b083b985-9410-409c-8f52-08d9883a8847

  Neptun_masterdata_validated:
    prod: 097d3c7c-4fcd-4b74-7084-08d98fa72496

  iKontrol_Data_Ingress:
    prod: 99c6b076-b6d2-475c-9be2-08d90a4e650d

  iKontrol_Data:
    prod: 31035e7e-7240-4e5d-9bea-08d90a4e650d

  Delfin_1_Minute_Resolution:
    prod: 55b1a30b-06e6-45d1-9be9-08d90a4e650d

  Olie_fladkable_readings_PT1M:
    prod: 025a6b59-5369-40ad-a87b-08d8de4f4dcb

  Olie_fladkable_readings_PT24H:
    prod: b9cc5c13-d1a8-4add-a87c-08d8de4f4dcb

  Olie_fladkabler_model_estimations:
    prod: bf97aca6-4f6a-44a4-a87e-08d8de4f4dcb

  Olie_fladkabler_probability_of_leak:
    prod: 3a882bda-04a1-4421-a880-08d8de4f4dcb

  Exchange_Rates_from_Danmarks_Nationalbank:
    prod: ed9700b3-59a1-47fd-dc29-08d945e7e910

  JAO_EDS:
    prod: 213defb0-ced9-40f3-dc2a-08d945e7e910

  DataHub_BI_Own_Consumption_Ingress:
    prod: fd558e4e-b032-42a0-6249-08d992ed010a

  DataHub_BI_Own_Consumption:
    prod: c456bc19-ce85-46b2-624b-08d992ed010a

  DataHub_BI_Hydro_Ingress:
    prod: c102a3cc-a7e4-438c-708d-08d98fa72496

  DataHub_BI_Hydro:
    prod: 351301a9-3b59-46d6-6241-08d992ed010a

  Swedish_and_Danish_Primary_Regulation_Ingress:
    prod: aa09478e-12c9-45ec-82af-08d9a02fd64d

  Swedish_and_Danish_Primary_Regulation:
    prod: 3b6adb7e-7d40-4bc9-82b1-08d9a02fd64d

  Nordpool_Special_Regulation_Volume_Ingress:
    prod: 99b0a0d3-8511-4464-82b2-08d9a02fd64d

  Nordpool_Special_Regulation_Volume:
    prod: b6583a22-3441-42a2-82b4-08d9a02fd64d
