scName: poc
nameSuffix: dev

vaultServer: <vault-server>
lokiServer: <loki-server>

destinationServer: <dest-server>

ingress:
  host: <host>
  loadBalancerIP: <ip>
  LoadBalancerResoureGroup: <rg>
  certmanagerissuer:  <cluster-issuer>
  # className: ingress-traefik

applications:
  argo-workflows: true
  argo-events: true
  argo-events-setup: true
  argo-events-azure: false
  cert-manager: true
  cert-manager-issuer: true
  external-secrets: true
  traefik: true
  jaeger-operator: true
  loki: true
  minio-operator: true
  prometheus: true
  thanos: true
  traefik-forward-auth: true
  vault: true

  # Transformations
  transform-dmi-weather: false
  i2et-sf6: true