scName: poc
nameSuffix: dev

vaultServer: <vault-server>
lokiServer: <loki-server>

destinationServer: localhost:443

ingress:
  host: <host>
  loadBalancerIP: <ip>
  LoadBalancerResoureGroup: <rg>
  certmanagerissuer: <cluster-issuer>
  # className: ingress-traefik

applications:
  argo-workflows: true
  argo-events: true
  argo-events-setup: true
  argo-events-azure: false
  cert-manager: true
  cert-manager-issuer: true
  external-secrets: true
  traefik: true
  jaeger-operator: true
  loki: true
  minio-operator: true
  prometheus: true
  thanos: true
  traefik-forward-auth: true
  vault: true

  # Data catalog
  datacatalog-secrets: true
  datacatalog-frontend: true
  datacatalog-backend: true

  # Osiris
  osiris-secrets: true
  osiris-ingress: true
  osiris-egress: true

  # Adapters
  adapters-secrets: true
  a-ikontrol: true

  # Transformations
  transformations-secrets: true
  t-datahub-bi-hydro: true
  t-datahub-bi-own-consumption: true
  t-dmi-weather: true
  t-i2et-gtms-alloc-bi: true
  t-i2et-gtms-balance-system-bi: true
  t-i2et-gtms-biocertificate-bi: true
  t-i2et-gtms-data-h-bi: true
  t-i2et-gtms-invoice-lines-bi: true
  t-i2et-gtms-nom-bi: true
  t-i2et-nordpool: true
  t-i2et-nordpool-special-regulation: true
  t-i2et-sf6: true
  t-ikontrol: true
  t-jao-monthly: true
  t-jao-yearly: true
  t-jao2eds: true
  t-neptun-1d: true
  t-neptun-1h: true
  t-neptun-3m: true
  t-neptun-masterdata: true
  t-oilcable-leakdetection: true
  t-svk-primary-regulation: true
