scName: poc
nameSuffix: dev

vaultServer: <vault-server>
lokiServer: <loki-server>

destinationServer: localhost:443

ingress:
  host: <host>
  loadBalancerIP: <ip>
  LoadBalancerResoureGroup: <rg>
  certmanagerissuer:  <cluster-issuer>
  # className: ingress-traefik

applications:
  argo-workflows: true
  argo-events: true
  argo-events-setup: true
  argo-events-azure: false
  cert-manager: true
  cert-manager-issuer: true
  external-secrets: true
  traefik: true
  jaeger-operator: true
  loki: true
  minio-operator: true
  prometheus: true
  thanos: true
  traefik-forward-auth: true
  vault: true

  # Data catalog
  datacatalog-secrets: true
  datacatalog-frontend: true
  datacatalog-backend: true

  # Osiris
  osiris-secrets: true
  osiris-ingress: true
  osiris-egress: true

  # Adapters
  a-ikontrol: true

  # Transformations
  t-i2et-sf6: true
  transformations-secrets: true

