name: argo-events-setup
clusterService: false
namespace: argo-events
destinationServer: https://env-ps-test-44fff1eb.hcp.westeurope.azmk8s.io:443
description: Argo events setup

project:
  name: argo-events-setup
  sourceRepos:
    - '*'

apps:
  - name: argo-events-setup
    source:
      repoURL: "https://github.com/Open-Olympus-Project/argo-events-setup.git"
      targetRevision: HEAD
      path: setup
      valuesFile: "argo-events-setup.yaml"

  - name: argo-events-azure
    source:
      repoURL: "https://github.com/Open-Olympus-Project/argo-events-setup.git"
      targetRevision: HEAD
      path: events-azure
      valuesFile: "argo-events-azure.yaml"
    ingressRoute:
      entryPoints:
        - websecure
      host: service-poc.westeurope.cloudapp.azure.com
      routes:
      - kind: Rule
        # Without host
        match: PathPrefix(`/argo-events/azure`)
        services:
          - name: azure-webhook-eventsource-svc
            port: 12000
      certificate:
        enabled: true
