name: transformations
clusterService: false
namespace: transformations
description: transformations
labels:
  app-type: transformations
  app-group: applications

apps:
  - name: transformations-secrets
    source:
      repoURL: "https://open-olympus-project.github.io/repo-helm"
      targetRevision: 0.1.3
      chart: "lethe"
      valuesFile: "lethe.yaml"

  # ingress2event-time
  - name: i2et-gtms-alloc-bi
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-gtms-alloc-bi.yaml"
  - name: i2et-gtms-balance-system-bi
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-gtms-balance-system-bi.yaml"
  - name: i2et-gtms-biocertificate-bi
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-gtms-biocertificate-bi.yaml"
  - name: i2et-gtms-data-h-bi
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-gtms-data-h-bi.yaml"
  - name: i2et-gtms-invoice-lines-bi
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-gtms-invoice-lines-bi.yaml"
  - name: i2et-gtms-nom-bi
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-gtms-nom-bi.yaml"
  - name: i2et-nordpool
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-nordpool.yaml"
  - name: i2et-nordpool-special-regulation
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-nordpool-special-regulation.yaml"
  - name: i2et-sf6
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-i2et-sf6.yaml"

  # DMI
  - name: dmi-weather
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-dmi-weather.yaml"

  # JAO
  - name: jao-monthly
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-jao-monthly.yaml"
  - name: jao-yearly
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-jao-yearly.yaml"
  - name: jao2eds
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-jao2eds.yaml"

  # Neptun
  - name: neptun-1d
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-neptun-1d.yaml"
  - name: neptun-1h
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-neptun-1h.yaml"
  - name: neptun-3m
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-neptun-3m.yaml"
  - name: neptun-masterdata
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-neptun-masterdata.yaml"

  # Ikontrol
  - name: ikontrol
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-ikontrol.yaml"

  # Oilcable-leakdetection
  - name: oilcable-leakdetection
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-oilcable-leakdetection.yaml"

  # Datahub
  - name: datahub-bi-hydro
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-datahub-bi-hydro.yaml"
  - name: datahub-bi-own-consumption
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-datahub-bi-own-consumption.yaml"

  # svk
  - name: svk-primary-regulation
    source:
      repoURL: "https://open-dataplatform.github.io/osiris-helm/"
      targetRevision: 0.1.12
      chart: "osiris-scheduler"
      valuesFile: "t-svk-primary-regulation.yaml"
