name: transformations
clusterService: false
namespace: transformations
description: transformations

project:
  name: transformations
  sourceRepos:
    - '*'

apps:
  - name: transform-dmi-weather
    source:
      repoURL: "https://github.com/Open-Dataplatform/transform-dmi-weather.git"
      targetRevision: feature/charts
      path: chart
      valuesFile: "transform-dmi-weather.yaml"
